<?php

namespace MdsSupportingClasses;

use ZipArchive;

class MdsLogger
{
    /**
     * @var string
     */
    private $log_dir = 'cache/mds_collivery/';

    /**
     * @var string
     */
    private $woo_log_source = 'mds_collivery';
    /**
     * @var int
     */
    private $max_log_bytes = 1048576;

    /**
     * @var int
     */
    private $throttle_seconds = 60;

    /**
     * @var array|null
     */
    private $throttle_state_cache = null;

    /**
     * @param string $log_dir
     */
    public function __construct($log_dir = null)
    {
        if ($log_dir !== null) {
            $this->log_dir = $log_dir;
        }
    }

    /**
     * Determines if a specific cache file exists and is valid.
     *
     * @param $name
     *
     * @return bool
     */
    public function has($name)
    {
        $log = $this->load($name);
        if ($log) {
            return $log;
        }

        return false;
    }

    /**
     * @param $function
     * @param $error
     * @param $settings
     * @param array $extraData
     */
    public function error($function, $error, $settings, $extraData = [])
    {
        if ($this->isThrottled('error', $function, $error)) {
            return;
        }

        $payload = array_filter([
            'function' => $function,
            'error' => $error,
        ]);

        if ($this->isDebugLoggingEnabled()) {
            $payload['settings'] = $settings;
            $payload['data'] = $extraData;
        }

        $this->put('error', $payload);
        $this->logToWoo('error', $function, $error, $settings, $extraData);
    }

    /**
     * @param $function
     * @param $error
     * @param $settings
     * @param array $extraData
     */
    public function warning($function, $error, $settings, $extraData = [])
    {
        if ($this->isThrottled('warning', $function, $error)) {
            return;
        }

        $payload = array_filter([
            'function' => $function,
            'error' => $error,
        ]);

        if ($this->isDebugLoggingEnabled()) {
            $payload['settings'] = $settings;
            $payload['data'] = $extraData;
        }

        $this->put('warning', $payload);
        $this->logToWoo('warning', $function, $error, $settings, $extraData);
    }

    /**
     * @param $message
     * @param array $data
     */
    public function success($message, $data = [])
    {
        $payload = array_filter([
            'message' => $message,
        ]);

        if ($this->isDebugLoggingEnabled()) {
            $payload['data'] = $data;
        }

        $this->put('success', $payload);
        $this->logToWoo('info', 'MdsLogger::success', $message, [], $data);
    }

    /**
     * Clear log files and throttle state.
     *
     * @return bool
     */
    public function clearLogFiles()
    {
        $files = [
            'error',
            'warning',
            'mdsWoocommerceLogs.zip',
            'log_state.json',
        ];

        $dir = $this->getLogDirectory();
        foreach ($files as $file) {
            $path = $dir.$file;
            if (file_exists($path)) {
                unlink($path);
            }
        }

        return true;
    }

    /**
     * Clear WooCommerce log files generated by this plugin.
     *
     * @return bool
     */
    public function clearWooLogFiles()
    {
        if (!function_exists('wc_get_logger')) {
            return false;
        }

        $logDir = null;
        if (class_exists('WC_Log_Handler_File') && method_exists('WC_Log_Handler_File', 'get_log_file_dir')) {
            $logDir = WC_Log_Handler_File::get_log_file_dir();
        } else {
            if (function_exists('wp_upload_dir')) {
                $uploads = wp_upload_dir();
                if (isset($uploads['basedir'])) {
                    $logDir = rtrim($uploads['basedir'], '/\\').'/wc-logs/';
                }
            }
        }

        if (!$logDir || !is_dir($logDir)) {
            return false;
        }

        $pattern = rtrim($logDir, '/\\').'/'.$this->woo_log_source.'-*.log*';
        foreach (glob($pattern) as $file) {
            if (is_file($file)) {
                unlink($file);
            }
        }

        return true;
    }

    /**
     * Mirror logs to WooCommerce logger when available.
     *
     * @param string $level
     * @param string $function
     * @param string $message
     * @param mixed  $settings
     * @param mixed  $extraData
     */
    private function logToWoo($level, $function, $message, $settings, $extraData)
    {
        if (!function_exists('wc_get_logger')) {
            return;
        }

        $logger = wc_get_logger();
        if (!$logger) {
            return;
        }

        $logMessage = $message;
        if ($function) {
            $logMessage = $function.': '.$message;
        }

        $context = [
            'source' => $this->woo_log_source,
        ];

        if (!empty($settings) && $this->isDebugLoggingEnabled()) {
            $context['settings'] = $this->sanitizeData($settings);
        }

        if (!empty($extraData) && $this->isDebugLoggingEnabled()) {
            $context['data'] = $this->sanitizeData($extraData);
        }

        $logger->log($level, $logMessage, $context);
    }

    /**
     * @return bool
     */
    private function isDebugLoggingEnabled()
    {
        if (!function_exists('get_option')) {
            return false;
        }

        $settings = get_option('woocommerce_mds_collivery_settings', []);
        if (!is_array($settings)) {
            return false;
        }

        return isset($settings['debug_logging']) && $settings['debug_logging'] === 'yes';
    }

    /**
     * @param string $level
     * @param string $function
     * @param string $message
     *
     * @return bool
     */
    private function isThrottled($level, $function, $message)
    {
        $state = $this->getThrottleState();
        $key = md5($level.'|'.$function.'|'.$message);
        $now = time();

        if (isset($state[$key]) && ($now - $state[$key]) < $this->throttle_seconds) {
            return true;
        }

        $state[$key] = $now;
        $this->setThrottleState($state);

        return false;
    }

    /**
     * @return array
     */
    private function getThrottleState()
    {
        if ($this->throttle_state_cache !== null) {
            return $this->throttle_state_cache;
        }

        $stateFile = $this->getLogDirectory().'log_state.json';
        if (file_exists($stateFile)) {
            $decoded = json_decode((string) file_get_contents($stateFile), true);
            if (is_array($decoded)) {
                $this->throttle_state_cache = $decoded;
                return $this->throttle_state_cache;
            }
        }

        $this->throttle_state_cache = [];
        return $this->throttle_state_cache;
    }

    /**
     * @param array $state
     */
    private function setThrottleState(array $state)
    {
        $stateFile = $this->getLogDirectory().'log_state.json';
        $this->create_dir($this->getLogDirectory());
        file_put_contents($stateFile, json_encode($state));
        $this->throttle_state_cache = $state;
    }

    /**
     * Remove sensitive values before logging.
     *
     * @param mixed $data
     * @return mixed
     */
    private function sanitizeData($data)
    {
        if (!is_array($data)) {
            return $data;
        }

        $redactKeys = [
            'mds_pass',
            'password',
            'api_token',
            'token',
        ];

        foreach ($data as $key => $value) {
            if (is_string($key) && in_array(strtolower($key), $redactKeys, true)) {
                $data[$key] = '[redacted]';
                continue;
            }

            if (is_array($value)) {
                $data[$key] = $this->sanitizeData($value);
            }
        }

        return $data;
    }

    /**
     * Gets a specific cache files contents.
     *
     * @param $name
     * @return mixed|null
     */
    public function get($name)
    {
        if ($log = $this->has($name)) {
            return json_decode($log);
        }

        return null;
    }

    /**
     * @return bool|string
     */
    public function zipLogFiles()
    {
        $files = [];

        foreach (['warning', 'error'] as $name) {
            if (file_exists($this->getLogDirectory().$name)) {
                $files[] = $this->getLogDirectory().$name;
            }
        }

        $zip = new ZipArchive();
        $zip_name = 'mdsWoocommerceLogs.zip';
        $zip_path = $this->getLogDirectory().$zip_name;
        if (file_exists($zip_path)) {
            unlink($zip_path);
        }

        if ($zip->open($zip_path, ZipArchive::CREATE) === true) {
            foreach ($files as $file) {
                $path_parts = pathinfo($file);
                $zip->addFile($file, $path_parts['basename']);
            }

            $zip->close();

            return $zip_path;
        } else {
            $this->error('MdsLogger:zipLogFiles', 'Unable to create zip file', []);
        }

        return false;
    }

    /**
     * @return string|null
     */
    public function downloadErrorFile()
    {
        if (file_exists($this->getLogDirectory().'error')) {
            return $this->getLogDirectory().'error';
        }
    }

    /**
     * Loads a specific log file else creates the log directory.
     *
     * @param $name
     *
     * @return mixed
     */
    protected function load($name)
    {
        if (file_exists($this->getLogDirectory().$name) && $content = file_get_contents($this->getLogDirectory().$name)) {
            return $content;
        } else {
            $this->create_dir($this->getLogDirectory());
        }
    }

    /**
     * Creates a specific cache file.
     *
     * @param $name
     * @param $value
     *
     * @return bool
     */
    protected function put($name, $value)
    {
        $this->rotateIfNeeded($name);
        if (file_exists($this->getLogDirectory().$name)) {
            if (filemtime($this->getLogDirectory().$name) < strtotime(date('Y-m-d').' 00:00:00')) {
                unlink($this->getLogDirectory().$name);
            }
        }

        if (file_put_contents($this->getLogDirectory().$name, json_encode([date('Y-m-d H:i:s') => $value], JSON_PRETTY_PRINT), FILE_APPEND)) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Rotate log file if it grows beyond the max size.
     *
     * @param string $name
     */
    private function rotateIfNeeded($name)
    {
        $path = $this->getLogDirectory().$name;
        if (!file_exists($path)) {
            return;
        }

        if (filesize($path) < $this->max_log_bytes) {
            return;
        }

        $timestamp = date('YmdHis');
        $rotated = $this->getLogDirectory().$name.'.'.$timestamp;
        rename($path, $rotated);
    }

    /**
     * Creates the cache directory.
     *
     * @param $dir_array
     */
    protected function create_dir($dir_array)
    {
        if (!is_array($dir_array)) {
            $dir_array = explode('/', $this->getLogDirectory());
        }

        array_pop($dir_array);
        $dir = implode('/', $dir_array);

        if ($dir != '' && !is_dir($dir)) {
            $this->create_dir($dir_array);
            mkdir($dir);
            chmod($dir, 755);
        }
    }

    /**
     * Gets the root cache directory not the admin one.
     *
     * @return string
     */
    public function getLogDirectory()
    {
        return ABSPATH.'/'.$this->log_dir;
    }
}
